# Generated by Django 3.0.1 on 2021-01-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210122_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
