# Generated by Django 3.0.1 on 2021-01-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_brand_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='side_banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
