# Generated by Django 3.0.1 on 2021-01-22 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_brand_side_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_1', models.CharField(max_length=254)),
                ('feature_2', models.CharField(max_length=254)),
                ('feature_3', models.CharField(max_length=254)),
                ('feature_4', models.CharField(max_length=254)),
                ('feature_5', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Key Features',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='key_features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.KeyFeatures'),
        ),
    ]
