# Generated by Django 3.0.1 on 2021-01-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210122_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='has_side_banner',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_5',
            field=models.TextField(),
        ),
    ]
