# Generated by Django 3.0.1 on 2021-01-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210122_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_logo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
