# Generated by Django 3.0.1 on 2021-01-23 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210123_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_logo',
        ),
    ]
