# Generated by Django 3.0.1 on 2021-01-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210123_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_logo_extra',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_logo_secundary',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
