# Generated by Django 3.0.1 on 2021-01-23 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210123_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_logo',
            new_name='extra_logo_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand_logo_extra',
            new_name='extra_logo_2',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='brand_logo_extra',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='brand_logo_secundary',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_logo_secundary',
        ),
    ]
