# Generated by Django 3.0.1 on 2021-01-23 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210123_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_logo_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_logo_1', to='products.Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='extra_logo_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_logo_2', to='products.Brand'),
        ),
    ]
