# Generated by Django 3.0.1 on 2021-01-23 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210123_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='extra_logo_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_logo_2',
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('manufacturer_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Brand')),
            ],
            options={
                'verbose_name_plural': 'Manufacturer',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='manufacter_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacter_1', to='products.Manufacturer'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacter_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacter_2', to='products.Manufacturer'),
        ),
    ]
