# Generated by Django 3.0.1 on 2021-01-23 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210123_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacter_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacter_2',
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_1', to='products.Manufacturer'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_2', to='products.Manufacturer'),
        ),
    ]
