# Generated by Django 3.0.1 on 2021-01-23 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210123_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='manufacturer_logo',
            new_name='logo',
        ),
    ]
