# Generated by Django 3.0.1 on 2021-01-23 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210123_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer_2',
        ),
        migrations.AddField(
            model_name='product',
            name='extra_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_logo', to='products.Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_logo', to='products.Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='processor_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processor_brand', to='products.Brand'),
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
