# Generated by Django 3.0.1 on 2021-01-23 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20210123_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='side_banners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='side_banners', to='products.Brand'),
        ),
    ]
