# Generated by Django 3.0.1 on 2021-01-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_side_banners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='extra_logo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='side_banners',
        ),
    ]
