# Generated by Django 3.0.1 on 2021-01-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210123_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='website',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
